### ISSUE TITLE
Le noeud Columns (Colonnes) de niveau base de données (level="Database" ) n'apparait pas ! 

### ISSUE THREAD

**Issue by hamidmira** [rudi-bruchez/SQLTrismegiste#1]
Le noeud Columns (Colonnes) de niveau base de données (level="Database" ) n'apparait pas dans l'arborescence de gauche (dans l'IHM)
Alors que le fichier Columns.xml existe bien dans le CorpusHermeticum. 
Cependant après analyse est génération des fichiers html  zipées , le fichier Columns.htm est bien généré 
NB : Ce problème est dû à une petie erreur qui s'est glissé dans le fichier **Columns.xml** 

Il manque le '**s**' à Databses 
folder="Database"   --> folder="Database**s**"  
Après ce correctif le noeud "Colonnes" réapparaît normalement  dans l'arborescence

**Comment by rudi-bruchez** [comment]
enfin corrigé !
