### ISSUE TITLE
Déclaration de la ressource  "XEvents" manquante ! 

### ISSUE THREAD

**Issue by hamidmira** [rudi-bruchez/SQLTrismegiste#2]
Plantage à l'exécution du programme ! 
En effet : 
1 - Il manque la déclation  de la ressource  **XEvents**
`<s:String x:Key="XEvents">XEvents</s:String>`
dans le fichier :   ..\SQLTrismegiste\SQLTrismegiste\Resources\FR.xaml

2 - Cf Issue #1 
Un petit loupé dans le correctif que tu as apporté ce matin à **Columns.xml** 
Il fallait rajouter  le 's'  de databases à la propriété **folder** et non pas à **level** 
Sauf erreur de ma part,  on devrait avoir ceci : 
`<hermeticus name="Columns" level="Database" folder="Databases"`
au lieu de la ligne actuelle (inversée)  ci-dessous :
`<hermeticus name="Columns" level="Databases" folder="Database"`

A+

**Comment by rudi-bruchez** [comment]
Hello, merci pour les deux bugs. En effet je voulais ajouter un onglet xevents mais finalement ça me semble too much, j'ai enlevé cet onglet dans le xaml de l'interface, je pousse cette modif pour que ce soit stable, il me reste à finir la traduction anglaise dans la ressource xaml.
