### ISSUE TITLE
Impossible d'effectuer un scroll vertical sur la grille "Base de données" de l'onglet "Connexion" 

### ISSUE THREAD

**Issue by hamidmira** [rudi-bruchez/SQLTrismegiste#5]
Bonjour, 
La grille (_DataGrid_ x:Name=_dgDatabases_"), de l'onglet "Connexion" ne permet pas d'effectuer un _scroll vertical_ lorsque la liste des bases de données est longue . 
La hauteur (Height) de la gille (_DataGrid_ x:Name=_dgDatabases_") est semble-t-il _automatique_ mais sans la possibilité donnée à l'utilisateur pour effectuer un scroll vertical. 
Lorsque la grille contient plusieurs dizaines de bases de données, dépassant la hauteur de l'écran, il devient impossible d'accéder et de sélectionner (cocher) les bases de données situées en bas de liste. Celles-ci sont invisibles et inaccessibles ! 
Il serait souhaitable, que la grille (_DataGrid_ x:Name=_dgDatabases_") s'adapte à la hauteur de l'écran tout en permettant, à l'utilisateur final, d'effectuer un _scroll vertical_, et ce, pour pouvoir accéder et sélectionner toutes les bases de données du Serveur. 

Merci. 
A+

**Comment by rudi-bruchez** [comment]
corrigé, je pousse un nouveau binaire

**Comment by hamidmira** [comment]
Super ! Merci d'avoir apporté les correctifs.
C'était un point bloquant sur certains serveurs !
