### ISSUE TITLE
Le répertoire des fichiers résultats html n'est pas réinitialisé lors d'une demande analyse ! 

### ISSUE THREAD

**Issue by hamidmira** [rudi-bruchez/SQLTrismegiste#7]
J'ai constaté que le répertoire "`C:\Users\<User_Name>\Documents\SQLTrismegiste\<Instance_Name>`\"
n'est pas réinitialisé (n'est pas vidé) lors de l'appui sur le bouton "`Lancer l'analyse`" et donc avant la génération de nouveaux fichiers html. 
Comme, je présume que les erreurs, sont gérées  ("catchées"), après la modification d'un fichier xml CorpusHermeticum, et en cas d'erreur, il n'est pas rare que l'on ne voit pas le résultat du nouveau fichier xml mis à jour, mais le résultat de l'ancien fichier xml, c.à.d , on visualise un ancien fichier html  du répertoire "`C:\Users\<User_Name>\Documents\SQLTrismegiste\<Instance_Name>\`"   ! 
ficher html généré par une ancienne analyse ! Cela devient très "perturbant" notamment en phase d'édition des fichiers xml  CorpusHermeticum
En conclusion : 
Je suggère de vider le répertoire "`C:\Users\<User_Name>\Documents\SQLTrismegiste\<Instance_Name\`" 
et ce, avant de générer de nouveau fichiers html lors d'un demande d'analyse. 

Merci. 

A+

**Comment by rudi-bruchez** [comment]
corrigé, il y a une nouvelle version au téléchargement

**Comment by hamidmira** [comment]
J'ai testé la nouvelle version, pour moi, tout est OK.
