### ISSUE TITLE
CorpusHermeticum : VolumeInfos.xml génère des erreurs en mode exécution !

### ISSUE THREAD

**Issue by hamidmira** [rudi-bruchez/SQLTrismegiste#8]
Le fichier **VolumeInfos.xml** gnère une erreur en mode exécution ! 
Le problème provient de la valeur attribuée à "**versionMajor**" 
En remplaçant la ligne  `<query versionMajor="11">`  par  `<query versionMajor="11-">` , l'erreur n’apparaît plus.  

Remarque  : 
Cette erreur se produit à l'identique, en mode exécution, et ce, pour les 10 autres fichiers xml  CorpusHermeticum ci-dessous :    

**MissingIndexWarnings.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**VLF.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**CardinalityEstimation.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**QueryExecutionCounts.xml**
Remplacer `<query versionMajor="11"> par <query versionMajor="11-">`

**SPExecutionCounts.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**SPAvgElapsedVariableTime.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**SPAvgElapsedTime.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**SPLogicalReads.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**SPWorkerTime.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

**TopIOStatements.xml**
Remplacer `<query versionMajor="11"> `par `<query versionMajor="11-">`

Merci. 

A+

**Comment by rudi-bruchez** [comment]
Normalement la nouvelle syntaxe est plutôt ceci : 
`<query versionMajor="11-*">`
pour dire : à partir de SQL Server 2012. Je vais corriger ça dans les xml

**Comment by rudi-bruchez** [comment]
corrigé, il y a une nouvelle version au téléchargement

**Comment by hamidmira** [comment]
J'ai testé la nouvelle version, pour moi, tout est OK par rapport la présente "Issue" #8 . A+
